version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: francescoxx/node_live_app
    ports:
      - "3000.3000"
    enviromment: 
      - PG_DB=node_live_db
      - PG_USER=francesco
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db

node_db:
  container_name: node_db
  image: postgres:12
  ports:
    - "5432:5432"
  enviromment: 
    - POSTGRES_DB=node_live_db
    - POSTGRES_USER=francsco
    - POSTGRES_PASSWORD=12345
  volumenes:
    -node_db_data:/var/lib/postgresql/data

volumenes:
  node_db_data: {}    